import Head from 'next/head'
import { Inter } from '@next/font/google'
import btn from '../styles/Button.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <h1>中間內容</h1>
        <h1 className='bg-bootstrap_primary'>自訂顏色2</h1>
        <h1 className='text-komabig'>中間內容</h1>
      </main>
      <button className='font-komafont'>測試內容的字體</button>
      <br/>
      <button className='transform translate-x-4 btn'>123</button>
      <br/>
      <button className={btn.bbtn}>測試apply樣式</button>
      <br/>
      <button className='animate-bounce'>測試animation</button>
    </>
  )
}
